name: build

on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Build and test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ubuntu dependencies
        run: >
          sudo apt-get install -y
          check
          lcov
          ninja-build
          valgrind

      - name: Install meson and coveralls
        run: pip install meson cpp-coveralls

      - name: Meson setup
        run: meson -Db_coverage=true builddir

      - name: Ninja build
        run: ninja -C builddir

      - name: Normal test
        id: normal_test
        run: meson test -C builddir

      - name: Valgring test
        id: valgring_test
        run: >
          meson test
          -C builddir
          --wrap='valgrind --leak-check=full --error-exitcode=1'
          -t 3
        env:
          CK_DEFAULT_TIMEOUT: 0

      - name: After failure
        uses: actions/upload-artifact@v3
        with:
          name: meson-testlog
          path: builddir/meson-logs/
        if: >
          failure() &&
          (steps.normal_test.outcome == 'failure' ||
          steps.valgring_test.outcome == 'failure')

      - name: Run lcov and send data to coveralls
        run: >
          coveralls
          --repo-token ${{ secrets.COVERALLS }}
          --root .
          --build-root builddir
          --exclude builddir/meson-private
          --exclude subprojects
          --exclude tests
          --exclude src/log.c
          --exclude src/logger.c
          --exclude src/main.c
          --exclude src/make_vcf.c
          --exclude src/merge_call.c
          --exclude src/process_sample.c
          --exclude src/sam.c
          --exclude src/thpool.c
          --exclude-pattern '.+\.h$'
          --gcov-options '\-lp'

